name: petgram

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Run install
      run: npm ci
    - name: Run build
      run: npm run build  
    - name: Run Clean Icons
      run: npm run cleanIcon
    - name: copy file via ssh key
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        rmRemote: true
        recursive: true
        local: "./www"
        remote: ${{ secrets.FOLDER_DESTINATION }}
        concurrency: 10
